# Generated by Django 4.1.3 on 2022-11-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedSentence',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('ENG', 'English'), ('FIL', 'Tagalog'), ('TAGLISH', 'Taglish')], max_length=10)),
                ('raw', models.TextField()),
                ('annotated', models.TextField()),
            ],
        ),
    ]
