# Generated by Django 4.1.4 on 2022-12-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0002_annotationchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedsentence',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotatedsentence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
