# Generated by Django 4.1.4 on 2022-12-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0003_annotatedsentence_extra_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationchangelog',
            name='description',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
