# Generated by Django 4.1.5 on 2023-01-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0005_annotatedsentence_is_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_model', models.BinaryField()),
                ('trained_on', models.DateTimeField(auto_now_add=True)),
                ('testing_set', models.ManyToManyField(to='tagger.annotatedsentence')),
            ],
        ),
    ]
