# Generated by Django 4.1.5 on 2023-01-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0006_onlinemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemodel',
            name='fmeasure_english',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='onlinemodel',
            name='fmeasure_tagalog',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='onlinemodel',
            name='fmeasure_taglish',
            field=models.FloatField(default=0),
        ),
    ]
